import { type NextPage } from 'next';
import Head from 'next/head';
import { Divider, Stack } from '@mantine/core';

import BaseLayout from 'components/BaseLayout';
import HeroTitle from 'components/HeroTitle';
import SignInForm from '../components/SignInForm';

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <BaseLayout>
        <Stack spacing="xl" align="center" style={{ maxWidth: '700px', margin: '48px auto 0' }}>
          <HeroTitle />
          <Divider orientation="vertical" />
          <SignInForm />
        </Stack>
      </BaseLayout>
    </>
  );
};

export default Home;
