/* eslint-disable max-len */
import { type Colors } from '@dealo/helpers';

export const CELL_STYLES: Record<Colors, string> = {
  'red': 'data-[active=true]:text-white data-[active=true]:bg-red-600 dark:data-[active=true]:bg-red-600',
  'orange': 'data-[active=true]:text-white data-[active=true]:bg-orange-600 dark:data-[active=true]:bg-orange-600',
  'amber': 'data-[active=true]:text-white data-[active=true]:bg-amber-600 dark:data-[active=true]:bg-amber-600',
  'yellow': 'data-[active=true]:text-white data-[active=true]:bg-yellow-600 dark:data-[active=true]:bg-yellow-600',
  'lime': 'data-[active=true]:text-white data-[active=true]:bg-lime-600 dark:data-[active=true]:bg-lime-600',
  'green': 'data-[active=true]:text-white data-[active=true]:bg-green-600 dark:data-[active=true]:bg-green-600',
  'emerald': 'data-[active=true]:text-white data-[active=true]:bg-emerald-600 dark:data-[active=true]:bg-emerald-600',
  'teal': 'data-[active=true]:text-white data-[active=true]:bg-teal-600 dark:data-[active=true]:bg-teal-600',
  'cyan': 'data-[active=true]:text-white data-[active=true]:bg-cyan-600 dark:data-[active=true]:bg-cyan-600',
  'sky': 'data-[active=true]:text-white data-[active=true]:bg-sky-600 dark:data-[active=true]:bg-sky-600',
  'blue': 'data-[active=true]:text-white data-[active=true]:bg-blue-600 dark:data-[active=true]:bg-blue-600',
  'indigo': 'data-[active=true]:text-white data-[active=true]:bg-indigo-600 dark:data-[active=true]:bg-indigo-600',
  'violet': 'data-[active=true]:text-white data-[active=true]:bg-violet-600 dark:data-[active=true]:bg-violet-600',
  'purple': 'data-[active=true]:text-white data-[active=true]:bg-purple-600 dark:data-[active=true]:bg-purple-600',
  'fuchsia': 'data-[active=true]:text-white data-[active=true]:bg-fuchsia-600 dark:data-[active=true]:bg-fuchsia-600',
  'pink': 'data-[active=true]:text-white data-[active=true]:bg-pink-600 dark:data-[active=true]:bg-pink-600',
  'rose': 'data-[active=true]:text-white data-[active=true]:bg-rose-600 dark:data-[active=true]:bg-rose-600',
};

export const ACTIVE_CELL_STYLES: Record<string, string> = {
  'red': 'group-hover:bg-red-200/10 data-[active=true]:text-white data-[active=true]:bg-red-600 group-hover:data-[active=true]:bg-red-500',
  'orange': 'group-hover:bg-orange-200/10 data-[active=true]:text-white data-[active=true]:bg-orange-600 group-hover:data-[active=true]:bg-orange-500',
  'amber': 'group-hover:bg-amber-200/10 data-[active=true]:text-white data-[active=true]:bg-amber-600 group-hover:data-[active=true]:bg-amber-500',
  'yellow': 'group-hover:bg-yellow-200/10 data-[active=true]:text-white data-[active=true]:bg-yellow-600 group-hover:data-[active=true]:bg-yellow-500',
  'lime': 'group-hover:bg-lime-200/10 data-[active=true]:text-white data-[active=true]:bg-lime-600 group-hover:data-[active=true]:bg-lime-500',
  'green': 'group-hover:bg-green-200/10 data-[active=true]:text-white data-[active=true]:bg-green-600 group-hover:data-[active=true]:bg-green-500',
  'emerald': 'group-hover:bg-slate-200/10 data-[active=true]:text-white data-[active=true]:bg-emerald-600 group-hover:data-[active=true]:bg-emerald-500',
  'teal': 'group-hover:bg-teal-200/10 data-[active=true]:text-white data-[active=true]:bg-teal-600 group-hover:data-[active=true]:bg-teal-500',
  'cyan': 'group-hover:bg-cyan-200/10 data-[active=true]:text-white data-[active=true]:bg-cyan-600 group-hover:data-[active=true]:bg-cyan-500',
  'sky': 'group-hover:bg-sky-200/10 data-[active=true]:text-white data-[active=true]:bg-sky-600 group-hover:data-[active=true]:bg-sky-500',
  'blue': 'group-hover:bg-blue-200/10 data-[active=true]:text-white data-[active=true]:bg-blue-600 group-hover:data-[active=true]:bg-blue-500',
  'indigo': 'group-hover:bg-indigo-200/10 data-[active=true]:text-white data-[active=true]:bg-indigo-600 group-hover:data-[active=true]:bg-indigo-500',
  'violet': 'group-hover:bg-violet-200/10 data-[active=true]:text-white data-[active=true]:bg-violet-600 group-hover:data-[active=true]:bg-violet-500',
  'purple': 'group-hover:bg-purple-200/10 data-[active=true]:text-white data-[active=true]:bg-purple-600 group-hover:data-[active=true]:bg-purple-500',
  'fuchsia': 'group-hover:bg-fuchsia-200/10 data-[active=true]:text-white data-[active=true]:bg-fuchsia-600 group-hover:data-[active=true]:bg-fuchsia-500',
  'pink': 'group-hover:bg-pink-200/10 data-[active=true]:text-white data-[active=true]:bg-pink-600 group-hover:data-[active=true]:bg-pink-500',
  'rose': 'group-hover:bg-rose-200/10 data-[active=true]:text-white data-[active=true]:bg-rose-600 group-hover:data-[active=true]:bg-rose-500',
};

export const FILLED_BUTTON_STYLES: Record<string, string> = {
  'red': 'text-red-600 bg-white',
  'orange': 'text-orange-600 bg-white',
  'amber': 'text-amber-600 bg-white',
  'yellow': 'text-yellow-600 bg-white',
  'lime': 'text-lime-600 bg-white',
  'green': 'text-green-600 bg-white',
  'emerald': 'text-emerald-600 bg-white',
  'teal': 'text-teal-600 bg-white',
  'cyan': 'text-cyan-600 bg-white',
  'sky': 'text-sky-600 bg-white',
  'blue': 'text-blue-600 bg-white',
  'indigo': 'text-indigo-600 bg-white',
  'violet': 'text-violet-600 bg-white',
  'purple': 'text-purple-600 bg-white',
  'fuchsia': 'text-fuchsia-600 bg-white',
  'pink': 'text-pink-600 bg-white',
  'rose': 'text-rose-600 bg-white',
}

export const OUTLINE_BUTTON_STYLES: Record<Colors, string> = {
  'red': 'border text-red-600 border-red-600 hover:border-red-600/90 hover:bg-red-600/5 dark:text-red-400 dark:border-red-400 dark:hover:border-red-400/90 dark:hover:text-red-400 dark:hover:bg-red-400/5',
  'orange': 'border text-orange-600 border-orange-600 hover:border-orange-600/90 hover:bg-orange-600/5 dark:text-orange-400 dark:border-orange-400 dark:hover:border-orange-400/90 dark:hover:text-orange-400 dark:hover:bg-orange-400/5',
  'amber': 'border text-amber-600 border-amber-600 hover:border-amber-600/90 hover:bg-amber-600/5 dark:text-amber-400 dark:border-amber-400 dark:hover:border-amber-400/90 dark:hover:text-amber-400 dark:hover:bg-amber-400/5',
  'yellow': 'border text-yellow-600 border-yellow-600 hover:border-yellow-600/90 hover:bg-yellow-600/5 dark:text-yellow-400 dark:border-yellow-400 dark:hover:border-yellow-400/90 dark:hover:text-yellow-400 dark:hover:bg-yellow-400/5',
  'lime': 'border text-lime-600 border-lime-600 hover:border-lime-600/90 hover:bg-lime-600/5 dark:text-lime-400 dark:border-lime-400 dark:hover:border-lime-400/90 dark:hover:text-lime-400 dark:hover:bg-lime-400/5',
  'green': 'border text-green-600 border-green-600 hover:border-green-600/90 hover:bg-green-600/5 dark:text-green-400 dark:border-green-400 dark:hover:border-green-400/90 dark:hover:text-green-400 dark:hover:bg-green-400/5',
  'emerald': 'border text-emerald-600 border-emerald-600 hover:border-emerald-600/90 hover:bg-emerald-600/5 dark:text-emerald-400 dark:border-emerald-400 dark:hover:border-emerald-400/90 dark:hover:text-emerald-400 dark:hover:bg-emerald-400/5',
  'teal': 'border text-teal-600 border-teal-600 hover:border-teal-600/90 hover:bg-teal-600/5 dark:text-teal-400 dark:border-teal-400 dark:hover:border-teal-400/90 dark:hover:text-teal-400 dark:hover:bg-teal-400/5',
  'cyan': 'border text-cyan-600 border-cyan-600 hover:border-cyan-600/90 hover:bg-cyan-600/5 dark:text-cyan-400 dark:border-cyan-400 dark:hover:border-cyan-400/90 dark:hover:text-cyan-400 dark:hover:bg-cyan-400/5',
  'sky': 'border text-sky-600 border-sky-600 hover:border-sky-600/90 hover:bg-sky-600/5 dark:text-sky-400 dark:border-sky-400 dark:hover:border-sky-400/90 dark:hover:text-sky-400 dark:hover:bg-sky-400/5',
  'blue': 'border text-blue-600 border-blue-600 hover:border-blue-600/90 hover:bg-blue-600/5 dark:text-blue-400 dark:border-blue-400 dark:hover:border-blue-400/90 dark:hover:text-blue-400 dark:hover:bg-blue-400/5',
  'indigo': 'border text-indigo-600 border-indigo-600 hover:border-indigo-600/90 hover:bg-indigo-600/5 dark:text-indigo-400 dark:border-indigo-400 dark:hover:border-indigo-400/90 dark:hover:text-indigo-400 dark:hover:bg-indigo-400/5',
  'violet': 'border text-violet-600 border-violet-600 hover:border-violet-600/90 hover:bg-violet-600/5 dark:text-violet-400 dark:border-violet-400 dark:hover:border-violet-400/90 dark:hover:text-violet-400 dark:hover:bg-violet-400/5',
  'purple': 'border text-purple-600 border-purple-600 hover:border-purple-600/90 hover:bg-purple-600/5 dark:text-purple-400 dark:border-purple-400 dark:hover:border-purple-400/90 dark:hover:text-purple-400 dark:hover:bg-purple-400/5',
  'fuchsia': 'border text-fuchsia-600 border-fuchsia-600 hover:border-fuchsia-600/90 hover:bg-fuchsia-600/5 dark:text-fuchsia-400 dark:border-fuchsia-400 dark:hover:border-fuchsia-400/90 dark:hover:text-fuchsia-400 dark:hover:bg-fuchsia-400/5',
  'pink': 'border text-pink-600 border-pink-600 hover:border-pink-600/90 hover:bg-pink-600/5 dark:text-pink-400 dark:border-pink-400 dark:hover:border-pink-400/90 dark:hover:text-pink-400 dark:hover:bg-pink-400/5',
  'rose': 'border text-rose-600 border-rose-600 hover:border-rose-600/90 hover:bg-rose-600/5 dark:text-rose-400 dark:border-rose-400 dark:hover:border-rose-400/90 dark:hover:text-rose-400 dark:hover:bg-rose-400/5',
}

export const MOBILE_FILLED_BUTTON_STYLES: Record<string, string> = {
  'red': 'bg-red-600 hover:bg-red-700 dark:hover:bg-red-500 text-white',
  'orange': 'bg-orange-600 hover:bg-orange-700 dark:hover:bg-orange-500 text-white',
  'amber': 'bg-amber-600 hover:bg-amber-700 dark:hover:bg-amber-500 text-white',
  'yellow': 'bg-yellow-600 hover:bg-yellow-700 dark:hover:bg-yellow-500 text-white',
  'lime': 'bg-lime-600 hover:bg-lime-700 dark:hover:bg-lime-500 text-white',
  'green': 'bg-green-600 hover:bg-green-700 dark:hover:bg-green-500 text-white',
  'emerald': 'bg-emerald-600 hover:bg-emerald-700 dark:hover:bg-emerald-500 text-white',
  'teal': 'bg-teal-600 hover:bg-teal-700 dark:hover:bg-teal-500 text-white',
  'cyan': 'bg-cyan-600 hover:bg-cyan-700 dark:hover:bg-cyan-500 text-white',
  'sky': 'bg-sky-600 hover:bg-sky-700 dark:hover:bg-sky-500 text-white',
  'blue': 'bg-blue-600 hover:bg-blue-700 dark:hover:bg-blue-500 text-white',
  'indigo': 'bg-indigo-600 hover:bg-indigo-700 dark:hover:bg-indigo-500 text-white',
  'violet': 'bg-violet-600 hover:bg-violet-700 dark:hover:bg-violet-500 text-white',
  'purple': 'bg-purple-600 hover:bg-purple-700 dark:hover:bg-purple-500 text-white',
  'fuchsia': 'bg-fuchsia-600 hover:bg-fuchsia-700 dark:hover:bg-fuchsia-500 text-white',
  'pink': 'bg-pink-600 hover:bg-pink-700 dark:hover:bg-pink-500 text-white',
  'rose': 'bg-rose-600 hover:bg-rose-700 dark:hover:bg-rose-500 text-white',
}

export const ACCORDION_HEADER_STYLES: Record<string, string> = {
  'red': 'data-[recommended=true]:text-red-500',
  'orange': 'data-[recommended=true]:text-orange-500',
  'amber': 'data-[recommended=true]:text-amber-500',
  'yellow': 'data-[recommended=true]:text-yellow-500',
  'lime': 'data-[recommended=true]:text-lime-500',
  'green': 'data-[recommended=true]:text-green-500',
  'emerald': 'data-[recommended=true]:text-emerald-500',
  'teal': 'data-[recommended=true]:text-teal-500',
  'cyan': 'data-[recommended=true]:text-cyan-500',
  'sky': 'data-[recommended=true]:text-sky-500',
  'blue': 'data-[recommended=true]:text-blue-500',
  'indigo': 'data-[recommended=true]:text-indigo-500',
  'violet': 'data-[recommended=true]:text-violet-500',
  'purple': 'data-[recommended=true]:text-purple-500',
  'fuchsia': 'data-[recommended=true]:text-fuchsia-500',
  'pink': 'data-[recommended=true]:text-pink-500',
  'rose': 'data-[recommended=true]:text-rose-600',
}
